
services:
  db:
    image: postgres
    restart: always
    container_name: postgresql_skillup
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: skillupdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - db

  web:
    build: .
    container_name: django_skillup
    command: python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: skillupdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - db

